//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LluviaTextureHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LluviaTextureHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accompanying Artwork.
        /// </summary>
        public static string AccompanyingArtwork {
            get {
                return ResourceManager.GetString("AccompanyingArtwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All-LN.
        /// </summary>
        public static string AllLN {
            get {
                return ResourceManager.GetString("AllLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbitrary texture.
        /// </summary>
        public static string ArbitraryTextures {
            get {
                return ResourceManager.GetString("ArbitraryTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoplay and Replay.
        /// </summary>
        public static string AutoplayAndReplay {
            get {
                return ResourceManager.GetString("AutoplayAndReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bombs.
        /// </summary>
        public static string Bombs {
            get {
                return ResourceManager.GetString("Bombs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM.
        /// </summary>
        public static string BPM {
            get {
                return ResourceManager.GetString("BPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas.
        /// </summary>
        public static string Canvas {
            get {
                return ResourceManager.GetString("Canvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic position.
        /// </summary>
        public static string ClassicPosition {
            get {
                return ResourceManager.GetString("ClassicPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns 1,3,5,7.
        /// </summary>
        public static string Columns1357 {
            get {
                return ResourceManager.GetString("Columns1357", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns 1,3,5,7 width.
        /// </summary>
        public static string Columns1357Width {
            get {
                return ResourceManager.GetString("Columns1357Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns 2,4,6.
        /// </summary>
        public static string Columns246 {
            get {
                return ResourceManager.GetString("Columns246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns 2,4,6 width.
        /// </summary>
        public static string Columns246Width {
            get {
                return ResourceManager.GetString("Columns246Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column separator.
        /// </summary>
        public static string ColumnSeparator {
            get {
                return ResourceManager.GetString("ColumnSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column separators width.
        /// </summary>
        public static string ColumnSeparatorsWidth {
            get {
                return ResourceManager.GetString("ColumnSeparatorsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companion.
        /// </summary>
        public static string Companion {
            get {
                return ResourceManager.GetString("Companion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down keys.
        /// </summary>
        public static string DownKeys {
            get {
                return ResourceManager.GetString("DownKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw keys.
        /// </summary>
        public static string DrawKeys {
            get {
                return ResourceManager.GetString("DrawKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw notes.
        /// </summary>
        public static string DrawNotes {
            get {
                return ResourceManager.GetString("DrawNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw playfield.
        /// </summary>
        public static string DrawPlayfield {
            get {
                return ResourceManager.GetString("DrawPlayfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the data in the JSON file..
        /// </summary>
        public static string Error_InvalidData {
            get {
                return ResourceManager.GetString("Error_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON data could not be parsed..
        /// </summary>
        public static string Error_JsonCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("Error_JsonCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract all from canvas.
        /// </summary>
        public static string ExtractAllFromCanvas {
            get {
                return ResourceManager.GetString("ExtractAllFromCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract from canvas.
        /// </summary>
        public static string ExtractFromCanvas {
            get {
                return ResourceManager.GetString("ExtractFromCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For verdict counter numbers.
        /// </summary>
        public static string ForVerdictCounterNumbers {
            get {
                return ResourceManager.GetString("ForVerdictCounterNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame height.
        /// </summary>
        public static string FrameHeight {
            get {
                return ResourceManager.GetString("FrameHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame quantity.
        /// </summary>
        public static string FrameQuantity {
            get {
                return ResourceManager.GetString("FrameQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame width.
        /// </summary>
        public static string FrameWidth {
            get {
                return ResourceManager.GetString("FrameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauges.
        /// </summary>
        public static string Gauges {
            get {
                return ResourceManager.GetString("Gauges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate preview.
        /// </summary>
        public static string GeneratePreview {
            get {
                return ResourceManager.GetString("GeneratePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global height.
        /// </summary>
        public static string GlobalHeight {
            get {
                return ResourceManager.GetString("GlobalHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global scale factor X.
        /// </summary>
        public static string GlobalScaleFactorX {
            get {
                return ResourceManager.GetString("GlobalScaleFactorX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global width.
        /// </summary>
        public static string GlobalWidth {
            get {
                return ResourceManager.GetString("GlobalWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global X.
        /// </summary>
        public static string GlobalX {
            get {
                return ResourceManager.GetString("GlobalX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Y.
        /// </summary>
        public static string GlobalY {
            get {
                return ResourceManager.GetString("GlobalY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health bar.
        /// </summary>
        public static string HealthBar {
            get {
                return ResourceManager.GetString("HealthBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health bar background.
        /// </summary>
        public static string HealthBarBackground {
            get {
                return ResourceManager.GetString("HealthBarBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height factor.
        /// </summary>
        public static string HeightFactor {
            get {
                return ResourceManager.GetString("HeightFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal fill.
        /// </summary>
        public static string HorizontalFill {
            get {
                return ResourceManager.GetString("HorizontalFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file.
        /// </summary>
        public static string ImageFile {
            get {
                return ResourceManager.GetString("ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual configurations.
        /// </summary>
        public static string IndividualConfigurations {
            get {
                return ResourceManager.GetString("IndividualConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection (AllLN).
        /// </summary>
        public static string Injection_AllLN {
            get {
                return ResourceManager.GetString("Injection_AllLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injections (Autoplay and replay).
        /// </summary>
        public static string Injection_AutoplayAndReplay {
            get {
                return ResourceManager.GetString("Injection_AutoplayAndReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injections (Gauges).
        /// </summary>
        public static string Injection_Gauges {
            get {
                return ResourceManager.GetString("Injection_Gauges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection (LR2 Normal judge).
        /// </summary>
        public static string Injection_LR2NMJudge {
            get {
                return ResourceManager.GetString("Injection_LR2NMJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection (No SSC).
        /// </summary>
        public static string Injection_NoSSC {
            get {
                return ResourceManager.GetString("Injection_NoSSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injections (Placement modifiers).
        /// </summary>
        public static string Injection_PlacementModifiers {
            get {
                return ResourceManager.GetString("Injection_PlacementModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injections.
        /// </summary>
        public static string Injections {
            get {
                return ResourceManager.GetString("Injections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert all in canvas.
        /// </summary>
        public static string InsertAllInCanvas {
            get {
                return ResourceManager.GetString("InsertAllInCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert in canvas.
        /// </summary>
        public static string InsertInCanvas {
            get {
                return ResourceManager.GetString("InsertInCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This skin component is already in the canvas..
        /// </summary>
        public static string InvalidOp_AlreadyInCanvas {
            get {
                return ResourceManager.GetString("InvalidOp_AlreadyInCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot load skin data if you have not opened both a JSON file and an image file..
        /// </summary>
        public static string InvalidOp_LoadSkinData {
            get {
                return ResourceManager.GetString("InvalidOp_LoadSkinData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The skin data is already loaded..
        /// </summary>
        public static string InvalidOp_SkinDataAlreadyLoaded {
            get {
                return ResourceManager.GetString("InvalidOp_SkinDataAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation.
        /// </summary>
        public static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON file.
        /// </summary>
        public static string JsonFile {
            get {
                return ResourceManager.GetString("JsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        public static string Keys {
            get {
                return ResourceManager.GetString("Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys (1,3,5,7).
        /// </summary>
        public static string Keys1357 {
            get {
                return ResourceManager.GetString("Keys1357", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys (2,4,6).
        /// </summary>
        public static string Keys246 {
            get {
                return ResourceManager.GetString("Keys246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys background.
        /// </summary>
        public static string KeysBackground {
            get {
                return ResourceManager.GetString("KeysBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser animations.
        /// </summary>
        public static string LaserAnimations {
            get {
                return ResourceManager.GetString("LaserAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lasers.
        /// </summary>
        public static string Lasers {
            get {
                return ResourceManager.GetString("Lasers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load skin data.
        /// </summary>
        public static string LoadSkinData {
            get {
                return ResourceManager.GetString("LoadSkinData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LR2NormalJudge.
        /// </summary>
        public static string LR2NormalJudge {
            get {
                return ResourceManager.GetString("LR2NormalJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        public static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxCombo.
        /// </summary>
        public static string MaxCombo {
            get {
                return ResourceManager.GetString("MaxCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mover.
        /// </summary>
        public static string Mover {
            get {
                return ResourceManager.GetString("Mover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No-SSC.
        /// </summary>
        public static string NoSSC {
            get {
                return ResourceManager.GetString("NoSSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin data loaded successfully.
        /// </summary>
        public static string Notification_Success_LoadSkinData {
            get {
                return ResourceManager.GetString("Notification_Success_LoadSkinData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task completed..
        /// </summary>
        public static string Notification_Success_TaskCompleted {
            get {
                return ResourceManager.GetString("Notification_Success_TaskCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers (Accuracy).
        /// </summary>
        public static string Numbers_Accuracy {
            get {
                return ResourceManager.GetString("Numbers_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers (BPM).
        /// </summary>
        public static string Numbers_BPM {
            get {
                return ResourceManager.GetString("Numbers_BPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers (COOL).
        /// </summary>
        public static string Numbers_COOL {
            get {
                return ResourceManager.GetString("Numbers_COOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers (Counter BAD).
        /// </summary>
        public static string Numbers_CounterBAD {
            get {
                return ResourceManager.GetString("Numbers_CounterBAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers (Counter COOL).
        /// </summary>
        public static string Numbers_CounterCOOL {
            get {
                return ResourceManager.GetString("Numbers_CounterCOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers (Counter GOOD).
        /// </summary>
        public static string Numbers_CounterGOOD {
            get {
                return ResourceManager.GetString("Numbers_CounterGOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers (Counter MISS).
        /// </summary>
        public static string Numbers_CounterMISS {
            get {
                return ResourceManager.GetString("Numbers_CounterMISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers (Counter OKAY).
        /// </summary>
        public static string Numbers_CounterOKAY {
            get {
                return ResourceManager.GetString("Numbers_CounterOKAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers (Health).
        /// </summary>
        public static string Numbers_Health {
            get {
                return ResourceManager.GetString("Numbers_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers (MaxCombo).
        /// </summary>
        public static string Numbers_MaxCombo {
            get {
                return ResourceManager.GetString("Numbers_MaxCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers (Offset).
        /// </summary>
        public static string Numbers_Offset {
            get {
                return ResourceManager.GetString("Numbers_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers (Scroll speed).
        /// </summary>
        public static string Numbers_ScrollSpeed {
            get {
                return ResourceManager.GetString("Numbers_ScrollSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers (Time).
        /// </summary>
        public static string Numbers_Time {
            get {
                return ResourceManager.GetString("Numbers_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset from left side.
        /// </summary>
        public static string OffsetFromLeftSide {
            get {
                return ResourceManager.GetString("OffsetFromLeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity factor.
        /// </summary>
        public static string OpacityFactor {
            get {
                return ResourceManager.GetString("OpacityFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open image file.
        /// </summary>
        public static string OpenImageFile {
            get {
                return ResourceManager.GetString("OpenImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open JSON file.
        /// </summary>
        public static string OpenJsonFile {
            get {
                return ResourceManager.GetString("OpenJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placard (Accuracy).
        /// </summary>
        public static string Placard_Accuracy {
            get {
                return ResourceManager.GetString("Placard_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placard (BAD).
        /// </summary>
        public static string Placard_BAD {
            get {
                return ResourceManager.GetString("Placard_BAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placard (BPM).
        /// </summary>
        public static string Placard_BPM {
            get {
                return ResourceManager.GetString("Placard_BPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placard (COOL).
        /// </summary>
        public static string Placard_COOL {
            get {
                return ResourceManager.GetString("Placard_COOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placard (GOOD).
        /// </summary>
        public static string Placard_GOOD {
            get {
                return ResourceManager.GetString("Placard_GOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placard (Health).
        /// </summary>
        public static string Placard_Health {
            get {
                return ResourceManager.GetString("Placard_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placard (MaxCombo).
        /// </summary>
        public static string Placard_MaxCombo {
            get {
                return ResourceManager.GetString("Placard_MaxCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placard (MISS).
        /// </summary>
        public static string Placard_MISS {
            get {
                return ResourceManager.GetString("Placard_MISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placard (Offset).
        /// </summary>
        public static string Placard_Offset {
            get {
                return ResourceManager.GetString("Placard_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placard (OKAY).
        /// </summary>
        public static string Placard_OKAY {
            get {
                return ResourceManager.GetString("Placard_OKAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placard (Scroll speed).
        /// </summary>
        public static string Placard_ScrollSpeed {
            get {
                return ResourceManager.GetString("Placard_ScrollSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placard (Time).
        /// </summary>
        public static string Placard_Time {
            get {
                return ResourceManager.GetString("Placard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placards.
        /// </summary>
        public static string Placards {
            get {
                return ResourceManager.GetString("Placards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement modifiers.
        /// </summary>
        public static string PlacementModifiers {
            get {
                return ResourceManager.GetString("PlacementModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playfield.
        /// </summary>
        public static string Playfield {
            get {
                return ResourceManager.GetString("Playfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playfield&apos;s border.
        /// </summary>
        public static string PlayfieldBorder {
            get {
                return ResourceManager.GetString("PlayfieldBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview skin.
        /// </summary>
        public static string PreviewSkin {
            get {
                return ResourceManager.GetString("PreviewSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank S.
        /// </summary>
        public static string Rank_S {
            get {
                return ResourceManager.GetString("Rank_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranks.
        /// </summary>
        public static string Ranks {
            get {
                return ResourceManager.GetString("Ranks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizer.
        /// </summary>
        public static string Resizer {
            get {
                return ResourceManager.GetString("Resizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll speed.
        /// </summary>
        public static string ScrollSpeed {
            get {
                return ResourceManager.GetString("ScrollSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin components.
        /// </summary>
        public static string SkinComponents {
            get {
                return ResourceManager.GetString("SkinComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin creator.
        /// </summary>
        public static string SkinCreator {
            get {
                return ResourceManager.GetString("SkinCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin attributions.
        /// </summary>
        public static string SkinCredits {
            get {
                return ResourceManager.GetString("SkinCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin name.
        /// </summary>
        public static string SkinName {
            get {
                return ResourceManager.GetString("SkinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin version.
        /// </summary>
        public static string SkinVersion {
            get {
                return ResourceManager.GetString("SkinVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload skin data.
        /// </summary>
        public static string UnloadSkinData {
            get {
                return ResourceManager.GetString("UnloadSkinData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up keys.
        /// </summary>
        public static string UpKeys {
            get {
                return ResourceManager.GetString("UpKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use accuracy placard.
        /// </summary>
        public static string UseAccuracyPlacard {
            get {
                return ResourceManager.GetString("UseAccuracyPlacard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use arbitrary texture.
        /// </summary>
        public static string UseArbitraryTexture {
            get {
                return ResourceManager.GetString("UseArbitraryTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use BPM placard.
        /// </summary>
        public static string UseBpmPlacard {
            get {
                return ResourceManager.GetString("UseBpmPlacard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use companion.
        /// </summary>
        public static string UseCompanion {
            get {
                return ResourceManager.GetString("UseCompanion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use health placard.
        /// </summary>
        public static string UseHealthPlacard {
            get {
                return ResourceManager.GetString("UseHealthPlacard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use max combo placard.
        /// </summary>
        public static string UseMaxComboPlacard {
            get {
                return ResourceManager.GetString("UseMaxComboPlacard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use offset placard.
        /// </summary>
        public static string UseOffsetPlacard {
            get {
                return ResourceManager.GetString("UseOffsetPlacard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use scroll speed placard.
        /// </summary>
        public static string UseScrollSpeedPlacard {
            get {
                return ResourceManager.GetString("UseScrollSpeedPlacard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use time placard.
        /// </summary>
        public static string UseTimePlacard {
            get {
                return ResourceManager.GetString("UseTimePlacard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use verdict count placards.
        /// </summary>
        public static string UseVerdictCountPlacards {
            get {
                return ResourceManager.GetString("UseVerdictCountPlacards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdict COOL.
        /// </summary>
        public static string Verdict_COOL {
            get {
                return ResourceManager.GetString("Verdict_COOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdict combo.
        /// </summary>
        public static string VerdictCombo {
            get {
                return ResourceManager.GetString("VerdictCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdict line.
        /// </summary>
        public static string VerdictLine {
            get {
                return ResourceManager.GetString("VerdictLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdicts.
        /// </summary>
        public static string Verdicts {
            get {
                return ResourceManager.GetString("Verdicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize.
        /// </summary>
        public static string Visualize {
            get {
                return ResourceManager.GetString("Visualize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpapers.
        /// </summary>
        public static string Wallpapers {
            get {
                return ResourceManager.GetString("Wallpapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width factor.
        /// </summary>
        public static string WidthFactor {
            get {
                return ResourceManager.GetString("WidthFactor", resourceCulture);
            }
        }
    }
}
